'use client'
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useRouter } from 'next/navigation'
import { Heart, Loader2, Mail, Lock, ArrowRight } from 'lucide-react'
export default function LoginPage() {
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [loading,setLoading]=useState(false);const [mode,setMode]=useState<'password'|'magic'>('password');const [message,setMessage]=useState('');const [error,setError]=useState('');const router=useRouter();const supabase=createClient()
  async function handleLogin(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');setMessage('')
    if(mode==='password'){const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);else{router.push('/');router.refresh()}}
    else{const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:`${window.location.origin}/api/auth/callback`}});if(error)setError(error.message);else setMessage('Check your email for a login link!')}
    setLoading(false)}
  return(<div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-50 via-white to-emerald-50/30"><div className="relative w-full max-w-md mx-4"><div className="text-center mb-8"><div className="inline-flex items-center justify-center w-14 h-14 rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-600 shadow-lg shadow-emerald-500/20 mb-4"><Heart className="w-7 h-7 text-white" fill="white"/></div><h1 className="text-2xl font-semibold text-slate-900">PrimeaHR</h1><p className="text-sm text-slate-500 mt-1">Beatrice Loving Heart</p></div><div className="bg-white rounded-2xl shadow-xl border border-slate-100 p-8"><h2 className="text-lg font-medium text-slate-900 mb-6">Sign in</h2><form onSubmit={handleLogin} className="space-y-4"><div><label className="block text-sm font-medium text-slate-700 mb-1.5">Email</label><div className="relative"><Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@beatricelovingheart.com" required className="w-full pl-10 pr-4 py-2.5 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500"/></div></div>{mode==='password'&&<div><label className="block text-sm font-medium text-slate-700 mb-1.5">Password</label><div className="relative"><Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required className="w-full pl-10 pr-4 py-2.5 border border-slate-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500"/></div></div>}{error&&<div className="text-sm text-red-600 bg-red-50 rounded-xl px-4 py-2.5">{error}</div>}{message&&<div className="text-sm text-emerald-700 bg-emerald-50 rounded-xl px-4 py-2.5">{message}</div>}<button type="submit" disabled={loading} className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-emerald-500 to-teal-600 text-white py-2.5 rounded-xl text-sm font-medium hover:from-emerald-600 hover:to-teal-700 disabled:opacity-50 shadow-lg shadow-emerald-500/20">{loading?<Loader2 className="w-4 h-4 animate-spin"/>:<>{mode==='password'?'Sign in':'Send magic link'}<ArrowRight className="w-4 h-4"/></>}</button></form><div className="mt-5 pt-5 border-t border-slate-100"><button onClick={()=>{setMode(mode==='password'?'magic':'password');setError('');setMessage('')}} className="w-full text-center text-sm text-slate-500 hover:text-emerald-600">{mode==='password'?'Sign in with magic link instead':'Sign in with password instead'}</button></div></div></div></div>)
}