'use client'
import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { Heart, LayoutDashboard, Users, Building2, Briefcase, FileText, ClipboardCheck, ClipboardList, BarChart3, Shield, Settings, LogOut, ChevronLeft, Menu } from 'lucide-react'
import { useState } from 'react'
import type { UserRole } from '@/types/database'
interface SidebarProps { user: { name: string; email: string; role: UserRole; avatarUrl: string|null } }
const nav=[{name:'Dashboard',href:'/',icon:LayoutDashboard},{name:'Employees',href:'/employees',icon:Users},{name:'Departments',href:'/departments',icon:Building2},{name:'Roles',href:'/roles',icon:Briefcase},{name:'Recruiting',href:'/recruiting',icon:ClipboardCheck},{name:'Offer Letters',href:'/offers',icon:FileText},{name:'Documents',href:'/documents',icon:FileText},{name:'Onboarding',href:'/onboarding',icon:ClipboardList},{name:'Analytics',href:'/analytics',icon:BarChart3},{name:'Compliance',href:'/compliance',icon:Shield},{name:'Settings',href:'/settings',icon:Settings}]
export function Sidebar({user}:SidebarProps){
  const pathname=usePathname();const router=useRouter();const [collapsed,setCollapsed]=useState(false);const [mobileOpen,setMobileOpen]=useState(false);const supabase=createClient()
  async function handleSignOut(){await supabase.auth.signOut();router.push('/login');router.refresh()}
  const isActive=(h:string)=>h==='/'?pathname==='/':pathname.startsWith(h)
  const rl:any={admin:'Administrator',hr_manager:'HR Manager',manager:'Manager',employee:'Employee',new_hire:'New Hire'}
  return(<><button onClick={()=>setMobileOpen(true)} className="lg:hidden fixed top-4 left-4 z-50 p-2 rounded-xl bg-slate-900 text-white shadow-lg"><Menu className="w-5 h-5"/></button>{mobileOpen&&<div className="lg:hidden fixed inset-0 z-40 bg-black/50 backdrop-blur-sm" onClick={()=>setMobileOpen(false)}/>}<aside className={`fixed lg:relative z-40 h-full bg-slate-900 transition-all duration-300 ${mobileOpen?'translate-x-0':'-translate-x-full lg:translate-x-0'} ${collapsed?'w-[68px]':'w-64'}`}><div className="flex flex-col h-full"><div className="flex items-center gap-3 px-4 py-5 border-b border-slate-800/50"><div className="flex-shrink-0 w-9 h-9 rounded-xl bg-gradient-to-br from-emerald-400 to-teal-500 flex items-center justify-center"><Heart className="w-5 h-5 text-white" fill="white"/></div>{!collapsed&&<div className="min-w-0"><h1 className="text-sm font-semibold text-white">PrimeaHR</h1><p className="text-[10px] text-slate-400 truncate">Beatrice Loving Heart</p></div>}<button onClick={()=>setCollapsed(!collapsed)} className="ml-auto p-1 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 hidden lg:flex"><ChevronLeft className={`w-4 h-4 transition-transform ${collapsed?'rotate-180':''}`}/></button></div><nav className="flex-1 px-3 py-4 space-y-1 overflow-auto">{nav.map(item=>{const active=isActive(item.href);return(<Link key={item.name} href={item.soon?'#':item.href} onClick={()=>setMobileOpen(false)} className={`flex items-center gap-3 px-3 py-2 rounded-xl text-sm font-medium transition-all relative ${active?'bg-emerald-500/15 text-emerald-400':item.soon?'text-slate-500 cursor-not-allowed':'text-slate-300 hover:bg-slate-800/60 hover:text-white'}`}><item.icon className={`w-[18px] h-[18px] flex-shrink-0 ${active?'text-emerald-400':''}`}/>{!collapsed&&<><span className="truncate">{item.name}</span>{item.soon&&<span className="ml-auto text-[9px] uppercase tracking-wider text-slate-600 bg-slate-800 px-1.5 py-0.5 rounded-full">Soon</span>}</>}{active&&<div className="absolute left-0 top-1/2 -translate-y-1/2 w-[3px] h-5 bg-emerald-400 rounded-r-full"/>}</Link>)})}</nav><div className="px-3 py-4 border-t border-slate-800/50"><div className="flex items-center gap-3 px-3 py-2"><div className="flex-shrink-0 w-8 h-8 rounded-full bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center text-white text-xs font-medium">{user.name.split(' ').map(n=>n[0]).join('').slice(0,2)}</div>{!collapsed&&<div className="min-w-0 flex-1"><p className="text-sm font-medium text-white truncate">{user.name}</p><p className="text-[10px] text-slate-400">{rl[user.role]}</p></div>}<button onClick={handleSignOut} title="Sign out" className="p-1.5 rounded-lg text-slate-400 hover:text-red-400 hover:bg-slate-800"><LogOut className="w-4 h-4"/></button></div></div></div></aside></>)
}