import { createClient } from '@/lib/supabase/server'
import { FileText, Plus, Clock, CheckCircle, XCircle, Send, Eye } from 'lucide-react'
import Link from 'next/link'
export default async function OffersPage() {
  const s = await createClient()
  const { data: offers } = await s.from('offer_letters').select('id, position_title, department, salary, status, created_at, sent_at, accepted_at, candidate:candidates(first_name, last_name, email), template:offer_letter_templates(name)').order('created_at', { ascending: false })
  const statusIcon: any = { draft: Clock, pending_approval: Eye, approved: CheckCircle, sent: Send, accepted: CheckCircle, declined: XCircle, expired: XCircle, revoked: XCircle }
  const statusColor: any = { draft: 'bg-slate-50 text-slate-600 border-slate-200', pending_approval: 'bg-blue-50 text-blue-700 border-blue-200', approved: 'bg-emerald-50 text-emerald-700 border-emerald-200', sent: 'bg-amber-50 text-amber-700 border-amber-200', accepted: 'bg-emerald-50 text-emerald-700 border-emerald-200', declined: 'bg-red-50 text-red-700 border-red-200', expired: 'bg-slate-50 text-slate-500 border-slate-200', revoked: 'bg-red-50 text-red-700 border-red-200' }
  return (<div><div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-semibold text-slate-900">Offer Letters</h1><p className="text-sm text-slate-500 mt-1">{offers?.length || 0} offer letters</p></div><Link href="/offers/new" className="flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-emerald-500 to-teal-600 text-white rounded-xl text-sm font-medium hover:from-emerald-600 hover:to-teal-700 shadow-lg shadow-emerald-500/20"><Plus className="w-4 h-4"/>Create Offer Letter</Link></div>{!offers?.length ? (<div className="bg-white rounded-2xl border border-slate-100 p-12 shadow-sm text-center"><FileText className="w-12 h-12 text-slate-300 mx-auto mb-3"/><p className="text-sm text-slate-500 mb-1">No offer letters yet</p><p className="text-xs text-slate-400">Create your first offer letter to get started.</p></div>) : (<div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-slate-100"><th className="text-left text-xs font-medium text-slate-500 uppercase tracking-wider px-5 py-3">Candidate</th><th className="text-left text-xs font-medium text-slate-500 uppercase tracking-wider px-5 py-3">Position</th><th className="text-left text-xs font-medium text-slate-500 uppercase tracking-wider px-5 py-3">Salary</th><th className="text-left text-xs font-medium text-slate-500 uppercase tracking-wider px-5 py-3">Status</th><th className="text-left text-xs font-medium text-slate-500 uppercase tracking-wider px-5 py-3">Created</th></tr></thead><tbody className="divide-y divide-slate-50">{(offers as any[]).map(o => { const SI = statusIcon[o.status] || Clock; return (<tr key={o.id} className="hover:bg-slate-50/50 cursor-pointer"><td className="px-5 py-3.5"><p className="text-sm font-medium text-slate-900">{o.candidate?.first_name} {o.candidate?.last_name}</p><p className="text-xs text-slate-400">{o.candidate?.email}</p></td><td className="px-5 py-3.5 text-sm text-slate-600">{o.position_title}</td><td className="px-5 py-3.5 text-sm text-slate-600">{o.salary ? '$' + Number(o.salary).toLocaleString() : '—'}</td><td className="px-5 py-3.5"><span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium border ${statusColor[o.status] || statusColor.draft}`}><SI className="w-3 h-3"/>{o.status.replace('_', ' ')}</span></td><td className="px-5 py-3.5 text-sm text-slate-500">{new Date(o.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</td></tr>)})}</tbody></table></div></div>)}</div>)
}